---
test:
  amazon_defaults: &amazon_defaults
    client_id: AMAZON_CLIENT_ID
    client_secret: AMAZON_CLIENT_SECRET
  amazon_eks_defaults: &amazon_eks_defaults
    hostname: hostname
    cluster_name: CLUSTER_NAME
    client_id: AMAZON_CLIENT_ID
    client_secret: AMAZON_CLIENT_SECRET
  amazon:
    <<: *amazon_defaults
  amazon_eks:
    <<: *amazon_eks_defaults
